//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadane relacji modelu EDM

[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_Kontrachenci_Adres", "Adres", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Adre), "Kontrachenci", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.Kontrachenci), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_Faktura_Kontrachenci", "Kontrachenci", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Kontrachenci), "Faktura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.Faktura), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_Faktura_SposubPlatnosci", "SposubPlatnosci", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.SposubPlatnosci), "Faktura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.Faktura), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_PozycjaFaktury_Faktura", "Faktura", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Faktura), "PozycjaFaktury", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.PozycjaFaktury), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_Kontrachenci_Rodzaj", "Rodzaj", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Rodzaj), "Kontrachenci", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.Kontrachenci), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_Kontrachenci_Status", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Status), "Kontrachenci", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.Kontrachenci), true)]
[assembly: EdmRelationshipAttribute("Faktury2022Model", "FK_PozycjaFaktury_Towar", "Towar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Firma.Models.Entities.Towar), "PozycjaFaktury", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Firma.Models.Entities.PozycjaFaktury), true)]

#endregion

namespace Firma.Models.Entities
{
    #region Konteksty
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    public partial class Faktury2022Entities : ObjectContext
    {
        #region Konstruktorzy
    
        /// <summary>
        /// Inicjuje nowy obiekt Faktury2022Entities, używając parametrów połączenia znalezionych w sekcji „Faktury2022Entities” pliku konfiguracyjnego aplikacji.
        /// </summary>
        public Faktury2022Entities() : base("name=Faktury2022Entities", "Faktury2022Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Zainicjuj nowy obiekt Faktury2022Entities.
        /// </summary>
        public Faktury2022Entities(string connectionString) : base(connectionString, "Faktury2022Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Zainicjuj nowy obiekt Faktury2022Entities.
        /// </summary>
        public Faktury2022Entities(EntityConnection connection) : base(connection, "Faktury2022Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Metody częściowe
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Właściwości elementu ObjectSet
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Adre> Adres
        {
            get
            {
                if ((_Adres == null))
                {
                    _Adres = base.CreateObjectSet<Adre>("Adres");
                }
                return _Adres;
            }
        }
        private ObjectSet<Adre> _Adres;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Faktura> Fakturas
        {
            get
            {
                if ((_Fakturas == null))
                {
                    _Fakturas = base.CreateObjectSet<Faktura>("Fakturas");
                }
                return _Fakturas;
            }
        }
        private ObjectSet<Faktura> _Fakturas;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Kontrachenci> Kontrachencis
        {
            get
            {
                if ((_Kontrachencis == null))
                {
                    _Kontrachencis = base.CreateObjectSet<Kontrachenci>("Kontrachencis");
                }
                return _Kontrachencis;
            }
        }
        private ObjectSet<Kontrachenci> _Kontrachencis;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<PozycjaFaktury> PozycjaFakturies
        {
            get
            {
                if ((_PozycjaFakturies == null))
                {
                    _PozycjaFakturies = base.CreateObjectSet<PozycjaFaktury>("PozycjaFakturies");
                }
                return _PozycjaFakturies;
            }
        }
        private ObjectSet<PozycjaFaktury> _PozycjaFakturies;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Rodzaj> Rodzajs
        {
            get
            {
                if ((_Rodzajs == null))
                {
                    _Rodzajs = base.CreateObjectSet<Rodzaj>("Rodzajs");
                }
                return _Rodzajs;
            }
        }
        private ObjectSet<Rodzaj> _Rodzajs;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<SposubPlatnosci> SposubPlatnoscis
        {
            get
            {
                if ((_SposubPlatnoscis == null))
                {
                    _SposubPlatnoscis = base.CreateObjectSet<SposubPlatnosci>("SposubPlatnoscis");
                }
                return _SposubPlatnoscis;
            }
        }
        private ObjectSet<SposubPlatnosci> _SposubPlatnoscis;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Status> Status
        {
            get
            {
                if ((_Status == null))
                {
                    _Status = base.CreateObjectSet<Status>("Status");
                }
                return _Status;
            }
        }
        private ObjectSet<Status> _Status;
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        public ObjectSet<Towar> Towars
        {
            get
            {
                if ((_Towars == null))
                {
                    _Towars = base.CreateObjectSet<Towar>("Towars");
                }
                return _Towars;
            }
        }
        private ObjectSet<Towar> _Towars;

        #endregion

        #region Metody AddTo
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Adres. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToAdres(Adre adre)
        {
            base.AddObject("Adres", adre);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Fakturas. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToFakturas(Faktura faktura)
        {
            base.AddObject("Fakturas", faktura);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Kontrachencis. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToKontrachencis(Kontrachenci kontrachenci)
        {
            base.AddObject("Kontrachencis", kontrachenci);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet PozycjaFakturies. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToPozycjaFakturies(PozycjaFaktury pozycjaFaktury)
        {
            base.AddObject("PozycjaFakturies", pozycjaFaktury);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Rodzajs. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRodzajs(Rodzaj rodzaj)
        {
            base.AddObject("Rodzajs", rodzaj);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet SposubPlatnoscis. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToSposubPlatnoscis(SposubPlatnosci sposubPlatnosci)
        {
            base.AddObject("SposubPlatnoscis", sposubPlatnosci);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Status. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToStatus(Status status)
        {
            base.AddObject("Status", status);
        }
    
        /// <summary>
        /// Przestarzała metoda dodawania nowego obiektu do elementu EntitySet Towars. metody .Add skojarzonej właściwości ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTowars(Towar towar)
        {
            base.AddObject("Towars", towar);
        }

        #endregion

    }

    #endregion

    #region Jednostki
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Adre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Adre : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Adre.
        /// </summary>
        /// <param name="idAdresu">Nieprawidłowa wartość właściwości IdAdresu.</param>
        public static Adre CreateAdre(global::System.Int32 idAdresu)
        {
            Adre adre = new Adre();
            adre.IdAdresu = idAdresu;
            return adre;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAdresu
        {
            get
            {
                return _IdAdresu;
            }
            set
            {
                if (_IdAdresu != value)
                {
                    OnIdAdresuChanging(value);
                    ReportPropertyChanging("IdAdresu");
                    _IdAdresu = StructuralObject.SetValidValue(value, "IdAdresu");
                    ReportPropertyChanged("IdAdresu");
                    OnIdAdresuChanged();
                }
            }
        }
        private global::System.Int32 _IdAdresu;
        partial void OnIdAdresuChanging(global::System.Int32 value);
        partial void OnIdAdresuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ulica
        {
            get
            {
                return _Ulica;
            }
            set
            {
                OnUlicaChanging(value);
                ReportPropertyChanging("Ulica");
                _Ulica = StructuralObject.SetValidValue(value, true, "Ulica");
                ReportPropertyChanged("Ulica");
                OnUlicaChanged();
            }
        }
        private global::System.String _Ulica;
        partial void OnUlicaChanging(global::System.String value);
        partial void OnUlicaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Miejscowosc
        {
            get
            {
                return _Miejscowosc;
            }
            set
            {
                OnMiejscowoscChanging(value);
                ReportPropertyChanging("Miejscowosc");
                _Miejscowosc = StructuralObject.SetValidValue(value, true, "Miejscowosc");
                ReportPropertyChanged("Miejscowosc");
                OnMiejscowoscChanged();
            }
        }
        private global::System.String _Miejscowosc;
        partial void OnMiejscowoscChanging(global::System.String value);
        partial void OnMiejscowoscChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NrLokalu
        {
            get
            {
                return _NrLokalu;
            }
            set
            {
                OnNrLokaluChanging(value);
                ReportPropertyChanging("NrLokalu");
                _NrLokalu = StructuralObject.SetValidValue(value, true, "NrLokalu");
                ReportPropertyChanged("NrLokalu");
                OnNrLokaluChanged();
            }
        }
        private global::System.String _NrLokalu;
        partial void OnNrLokaluChanging(global::System.String value);
        partial void OnNrLokaluChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NrDomu
        {
            get
            {
                return _NrDomu;
            }
            set
            {
                OnNrDomuChanging(value);
                ReportPropertyChanging("NrDomu");
                _NrDomu = StructuralObject.SetValidValue(value, true, "NrDomu");
                ReportPropertyChanged("NrDomu");
                OnNrDomuChanged();
            }
        }
        private global::System.String _NrDomu;
        partial void OnNrDomuChanging(global::System.String value);
        partial void OnNrDomuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KodPocztowy
        {
            get
            {
                return _KodPocztowy;
            }
            set
            {
                OnKodPocztowyChanging(value);
                ReportPropertyChanging("KodPocztowy");
                _KodPocztowy = StructuralObject.SetValidValue(value, true, "KodPocztowy");
                ReportPropertyChanged("KodPocztowy");
                OnKodPocztowyChanged();
            }
        }
        private global::System.String _KodPocztowy;
        partial void OnKodPocztowyChanging(global::System.String value);
        partial void OnKodPocztowyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Poczta
        {
            get
            {
                return _Poczta;
            }
            set
            {
                OnPocztaChanging(value);
                ReportPropertyChanging("Poczta");
                _Poczta = StructuralObject.SetValidValue(value, true, "Poczta");
                ReportPropertyChanged("Poczta");
                OnPocztaChanged();
            }
        }
        private global::System.String _Poczta;
        partial void OnPocztaChanging(global::System.String value);
        partial void OnPocztaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kraj
        {
            get
            {
                return _Kraj;
            }
            set
            {
                OnKrajChanging(value);
                ReportPropertyChanging("Kraj");
                _Kraj = StructuralObject.SetValidValue(value, true, "Kraj");
                ReportPropertyChanged("Kraj");
                OnKrajChanged();
            }
        }
        private global::System.String _Kraj;
        partial void OnKrajChanging(global::System.String value);
        partial void OnKrajChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Adres", "Kontrachenci")]
        public EntityCollection<Kontrachenci> Kontrachencis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Adres", "Kontrachenci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Adres", "Kontrachenci", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Faktura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Faktura : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Faktura.
        /// </summary>
        /// <param name="idFaktury">Nieprawidłowa wartość właściwości IdFaktury.</param>
        public static Faktura CreateFaktura(global::System.Int32 idFaktury)
        {
            Faktura faktura = new Faktura();
            faktura.IdFaktury = idFaktury;
            return faktura;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFaktury
        {
            get
            {
                return _IdFaktury;
            }
            set
            {
                if (_IdFaktury != value)
                {
                    OnIdFakturyChanging(value);
                    ReportPropertyChanging("IdFaktury");
                    _IdFaktury = StructuralObject.SetValidValue(value, "IdFaktury");
                    ReportPropertyChanged("IdFaktury");
                    OnIdFakturyChanged();
                }
            }
        }
        private global::System.Int32 _IdFaktury;
        partial void OnIdFakturyChanging(global::System.Int32 value);
        partial void OnIdFakturyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numer
        {
            get
            {
                return _Numer;
            }
            set
            {
                OnNumerChanging(value);
                ReportPropertyChanging("Numer");
                _Numer = StructuralObject.SetValidValue(value, true, "Numer");
                ReportPropertyChanged("Numer");
                OnNumerChanged();
            }
        }
        private global::System.String _Numer;
        partial void OnNumerChanging(global::System.String value);
        partial void OnNumerChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataWystawienia
        {
            get
            {
                return _DataWystawienia;
            }
            set
            {
                OnDataWystawieniaChanging(value);
                ReportPropertyChanging("DataWystawienia");
                _DataWystawienia = StructuralObject.SetValidValue(value, "DataWystawienia");
                ReportPropertyChanged("DataWystawienia");
                OnDataWystawieniaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataWystawienia;
        partial void OnDataWystawieniaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataWystawieniaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdKnotrachenta
        {
            get
            {
                return _IdKnotrachenta;
            }
            set
            {
                OnIdKnotrachentaChanging(value);
                ReportPropertyChanging("IdKnotrachenta");
                _IdKnotrachenta = StructuralObject.SetValidValue(value, "IdKnotrachenta");
                ReportPropertyChanged("IdKnotrachenta");
                OnIdKnotrachentaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdKnotrachenta;
        partial void OnIdKnotrachentaChanging(Nullable<global::System.Int32> value);
        partial void OnIdKnotrachentaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TerminPlatnosci
        {
            get
            {
                return _TerminPlatnosci;
            }
            set
            {
                OnTerminPlatnosciChanging(value);
                ReportPropertyChanging("TerminPlatnosci");
                _TerminPlatnosci = StructuralObject.SetValidValue(value, "TerminPlatnosci");
                ReportPropertyChanged("TerminPlatnosci");
                OnTerminPlatnosciChanged();
            }
        }
        private Nullable<global::System.DateTime> _TerminPlatnosci;
        partial void OnTerminPlatnosciChanging(Nullable<global::System.DateTime> value);
        partial void OnTerminPlatnosciChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdSposobuPlatnosci
        {
            get
            {
                return _IdSposobuPlatnosci;
            }
            set
            {
                OnIdSposobuPlatnosciChanging(value);
                ReportPropertyChanging("IdSposobuPlatnosci");
                _IdSposobuPlatnosci = StructuralObject.SetValidValue(value, "IdSposobuPlatnosci");
                ReportPropertyChanged("IdSposobuPlatnosci");
                OnIdSposobuPlatnosciChanged();
            }
        }
        private Nullable<global::System.Int32> _IdSposobuPlatnosci;
        partial void OnIdSposobuPlatnosciChanging(Nullable<global::System.Int32> value);
        partial void OnIdSposobuPlatnosciChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyZatwierdzone
        {
            get
            {
                return _CzyZatwierdzone;
            }
            set
            {
                OnCzyZatwierdzoneChanging(value);
                ReportPropertyChanging("CzyZatwierdzone");
                _CzyZatwierdzone = StructuralObject.SetValidValue(value, "CzyZatwierdzone");
                ReportPropertyChanged("CzyZatwierdzone");
                OnCzyZatwierdzoneChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyZatwierdzone;
        partial void OnCzyZatwierdzoneChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyZatwierdzoneChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywna
        {
            get
            {
                return _CzyAktywna;
            }
            set
            {
                OnCzyAktywnaChanging(value);
                ReportPropertyChanging("CzyAktywna");
                _CzyAktywna = StructuralObject.SetValidValue(value, "CzyAktywna");
                ReportPropertyChanged("CzyAktywna");
                OnCzyAktywnaChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywna;
        partial void OnCzyAktywnaChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnaChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Faktura_Kontrachenci", "Kontrachenci")]
        public Kontrachenci Kontrachenci
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontrachenci>("Faktury2022Model.FK_Faktura_Kontrachenci", "Kontrachenci").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontrachenci>("Faktury2022Model.FK_Faktura_Kontrachenci", "Kontrachenci").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kontrachenci> KontrachenciReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kontrachenci>("Faktury2022Model.FK_Faktura_Kontrachenci", "Kontrachenci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kontrachenci>("Faktury2022Model.FK_Faktura_Kontrachenci", "Kontrachenci", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Faktura_SposubPlatnosci", "SposubPlatnosci")]
        public SposubPlatnosci SposubPlatnosci
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SposubPlatnosci>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "SposubPlatnosci").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SposubPlatnosci>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "SposubPlatnosci").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SposubPlatnosci> SposubPlatnosciReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SposubPlatnosci>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "SposubPlatnosci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SposubPlatnosci>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "SposubPlatnosci", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_PozycjaFaktury_Faktura", "PozycjaFaktury")]
        public EntityCollection<PozycjaFaktury> PozycjaFakturies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PozycjaFaktury>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "PozycjaFaktury");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PozycjaFaktury>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "PozycjaFaktury", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Kontrachenci")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kontrachenci : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Kontrachenci.
        /// </summary>
        /// <param name="idKontrachenta">Nieprawidłowa wartość właściwości IdKontrachenta.</param>
        public static Kontrachenci CreateKontrachenci(global::System.Int32 idKontrachenta)
        {
            Kontrachenci kontrachenci = new Kontrachenci();
            kontrachenci.IdKontrachenta = idKontrachenta;
            return kontrachenci;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdKontrachenta
        {
            get
            {
                return _IdKontrachenta;
            }
            set
            {
                if (_IdKontrachenta != value)
                {
                    OnIdKontrachentaChanging(value);
                    ReportPropertyChanging("IdKontrachenta");
                    _IdKontrachenta = StructuralObject.SetValidValue(value, "IdKontrachenta");
                    ReportPropertyChanged("IdKontrachenta");
                    OnIdKontrachentaChanged();
                }
            }
        }
        private global::System.Int32 _IdKontrachenta;
        partial void OnIdKontrachentaChanging(global::System.Int32 value);
        partial void OnIdKontrachentaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kod
        {
            get
            {
                return _Kod;
            }
            set
            {
                OnKodChanging(value);
                ReportPropertyChanging("Kod");
                _Kod = StructuralObject.SetValidValue(value, true, "Kod");
                ReportPropertyChanged("Kod");
                OnKodChanged();
            }
        }
        private global::System.String _Kod;
        partial void OnKodChanging(global::System.String value);
        partial void OnKodChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIP
        {
            get
            {
                return _NIP;
            }
            set
            {
                OnNIPChanging(value);
                ReportPropertyChanging("NIP");
                _NIP = StructuralObject.SetValidValue(value, true, "NIP");
                ReportPropertyChanged("NIP");
                OnNIPChanged();
            }
        }
        private global::System.String _NIP;
        partial void OnNIPChanging(global::System.String value);
        partial void OnNIPChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdRodzaju
        {
            get
            {
                return _IdRodzaju;
            }
            set
            {
                OnIdRodzajuChanging(value);
                ReportPropertyChanging("IdRodzaju");
                _IdRodzaju = StructuralObject.SetValidValue(value, "IdRodzaju");
                ReportPropertyChanged("IdRodzaju");
                OnIdRodzajuChanged();
            }
        }
        private Nullable<global::System.Int32> _IdRodzaju;
        partial void OnIdRodzajuChanging(Nullable<global::System.Int32> value);
        partial void OnIdRodzajuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdStatusu
        {
            get
            {
                return _IdStatusu;
            }
            set
            {
                OnIdStatusuChanging(value);
                ReportPropertyChanging("IdStatusu");
                _IdStatusu = StructuralObject.SetValidValue(value, "IdStatusu");
                ReportPropertyChanged("IdStatusu");
                OnIdStatusuChanged();
            }
        }
        private Nullable<global::System.Int32> _IdStatusu;
        partial void OnIdStatusuChanging(Nullable<global::System.Int32> value);
        partial void OnIdStatusuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdAdresu
        {
            get
            {
                return _IdAdresu;
            }
            set
            {
                OnIdAdresuChanging(value);
                ReportPropertyChanging("IdAdresu");
                _IdAdresu = StructuralObject.SetValidValue(value, "IdAdresu");
                ReportPropertyChanged("IdAdresu");
                OnIdAdresuChanged();
            }
        }
        private Nullable<global::System.Int32> _IdAdresu;
        partial void OnIdAdresuChanging(Nullable<global::System.Int32> value);
        partial void OnIdAdresuChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Adres", "Adres")]
        public Adre Adre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Adre>("Faktury2022Model.FK_Kontrachenci_Adres", "Adres").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Adre>("Faktury2022Model.FK_Kontrachenci_Adres", "Adres").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Adre> AdreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Adre>("Faktury2022Model.FK_Kontrachenci_Adres", "Adres");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Adre>("Faktury2022Model.FK_Kontrachenci_Adres", "Adres", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Faktura_Kontrachenci", "Faktura")]
        public EntityCollection<Faktura> Fakturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Faktura>("Faktury2022Model.FK_Faktura_Kontrachenci", "Faktura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Faktura>("Faktury2022Model.FK_Faktura_Kontrachenci", "Faktura", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Rodzaj", "Rodzaj")]
        public Rodzaj Rodzaj
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rodzaj>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Rodzaj").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rodzaj>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Rodzaj").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rodzaj> RodzajReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rodzaj>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Rodzaj");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rodzaj>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Rodzaj", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Status", "Status")]
        public Status Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("Faktury2022Model.FK_Kontrachenci_Status", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("Faktury2022Model.FK_Kontrachenci_Status", "Status").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("Faktury2022Model.FK_Kontrachenci_Status", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("Faktury2022Model.FK_Kontrachenci_Status", "Status", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="PozycjaFaktury")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PozycjaFaktury : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt PozycjaFaktury.
        /// </summary>
        /// <param name="idPozycjiFaktury">Nieprawidłowa wartość właściwości IdPozycjiFaktury.</param>
        public static PozycjaFaktury CreatePozycjaFaktury(global::System.Int32 idPozycjiFaktury)
        {
            PozycjaFaktury pozycjaFaktury = new PozycjaFaktury();
            pozycjaFaktury.IdPozycjiFaktury = idPozycjiFaktury;
            return pozycjaFaktury;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPozycjiFaktury
        {
            get
            {
                return _IdPozycjiFaktury;
            }
            set
            {
                if (_IdPozycjiFaktury != value)
                {
                    OnIdPozycjiFakturyChanging(value);
                    ReportPropertyChanging("IdPozycjiFaktury");
                    _IdPozycjiFaktury = StructuralObject.SetValidValue(value, "IdPozycjiFaktury");
                    ReportPropertyChanged("IdPozycjiFaktury");
                    OnIdPozycjiFakturyChanged();
                }
            }
        }
        private global::System.Int32 _IdPozycjiFaktury;
        partial void OnIdPozycjiFakturyChanging(global::System.Int32 value);
        partial void OnIdPozycjiFakturyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTowaru
        {
            get
            {
                return _IdTowaru;
            }
            set
            {
                OnIdTowaruChanging(value);
                ReportPropertyChanging("IdTowaru");
                _IdTowaru = StructuralObject.SetValidValue(value, "IdTowaru");
                ReportPropertyChanged("IdTowaru");
                OnIdTowaruChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTowaru;
        partial void OnIdTowaruChanging(Nullable<global::System.Int32> value);
        partial void OnIdTowaruChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFaktury
        {
            get
            {
                return _IdFaktury;
            }
            set
            {
                OnIdFakturyChanging(value);
                ReportPropertyChanging("IdFaktury");
                _IdFaktury = StructuralObject.SetValidValue(value, "IdFaktury");
                ReportPropertyChanged("IdFaktury");
                OnIdFakturyChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFaktury;
        partial void OnIdFakturyChanging(Nullable<global::System.Int32> value);
        partial void OnIdFakturyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cena
        {
            get
            {
                return _Cena;
            }
            set
            {
                OnCenaChanging(value);
                ReportPropertyChanging("Cena");
                _Cena = StructuralObject.SetValidValue(value, "Cena");
                ReportPropertyChanged("Cena");
                OnCenaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cena;
        partial void OnCenaChanging(Nullable<global::System.Decimal> value);
        partial void OnCenaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Ilosc
        {
            get
            {
                return _Ilosc;
            }
            set
            {
                OnIloscChanging(value);
                ReportPropertyChanging("Ilosc");
                _Ilosc = StructuralObject.SetValidValue(value, "Ilosc");
                ReportPropertyChanged("Ilosc");
                OnIloscChanged();
            }
        }
        private Nullable<global::System.Decimal> _Ilosc;
        partial void OnIloscChanging(Nullable<global::System.Decimal> value);
        partial void OnIloscChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Rabat
        {
            get
            {
                return _Rabat;
            }
            set
            {
                OnRabatChanging(value);
                ReportPropertyChanging("Rabat");
                _Rabat = StructuralObject.SetValidValue(value, "Rabat");
                ReportPropertyChanged("Rabat");
                OnRabatChanged();
            }
        }
        private Nullable<global::System.Decimal> _Rabat;
        partial void OnRabatChanging(Nullable<global::System.Decimal> value);
        partial void OnRabatChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_PozycjaFaktury_Faktura", "Faktura")]
        public Faktura Faktura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Faktura>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "Faktura").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Faktura>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "Faktura").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Faktura> FakturaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Faktura>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "Faktura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Faktura>("Faktury2022Model.FK_PozycjaFaktury_Faktura", "Faktura", value);
                }
            }
        }
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_PozycjaFaktury_Towar", "Towar")]
        public Towar Towar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Towar>("Faktury2022Model.FK_PozycjaFaktury_Towar", "Towar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Towar>("Faktury2022Model.FK_PozycjaFaktury_Towar", "Towar").Value = value;
            }
        }
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Towar> TowarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Towar>("Faktury2022Model.FK_PozycjaFaktury_Towar", "Towar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Towar>("Faktury2022Model.FK_PozycjaFaktury_Towar", "Towar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Rodzaj")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rodzaj : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Rodzaj.
        /// </summary>
        /// <param name="idRodzaju">Nieprawidłowa wartość właściwości IdRodzaju.</param>
        public static Rodzaj CreateRodzaj(global::System.Int32 idRodzaju)
        {
            Rodzaj rodzaj = new Rodzaj();
            rodzaj.IdRodzaju = idRodzaju;
            return rodzaj;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRodzaju
        {
            get
            {
                return _IdRodzaju;
            }
            set
            {
                if (_IdRodzaju != value)
                {
                    OnIdRodzajuChanging(value);
                    ReportPropertyChanging("IdRodzaju");
                    _IdRodzaju = StructuralObject.SetValidValue(value, "IdRodzaju");
                    ReportPropertyChanged("IdRodzaju");
                    OnIdRodzajuChanged();
                }
            }
        }
        private global::System.Int32 _IdRodzaju;
        partial void OnIdRodzajuChanging(global::System.Int32 value);
        partial void OnIdRodzajuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opis
        {
            get
            {
                return _Opis;
            }
            set
            {
                OnOpisChanging(value);
                ReportPropertyChanging("Opis");
                _Opis = StructuralObject.SetValidValue(value, true, "Opis");
                ReportPropertyChanged("Opis");
                OnOpisChanged();
            }
        }
        private global::System.String _Opis;
        partial void OnOpisChanging(global::System.String value);
        partial void OnOpisChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> czyAktywny
        {
            get
            {
                return _czyAktywny;
            }
            set
            {
                OnczyAktywnyChanging(value);
                ReportPropertyChanging("czyAktywny");
                _czyAktywny = StructuralObject.SetValidValue(value, "czyAktywny");
                ReportPropertyChanged("czyAktywny");
                OnczyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _czyAktywny;
        partial void OnczyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnczyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Rodzaj", "Kontrachenci")]
        public EntityCollection<Kontrachenci> Kontrachencis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Kontrachenci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Rodzaj", "Kontrachenci", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="SposubPlatnosci")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SposubPlatnosci : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt SposubPlatnosci.
        /// </summary>
        /// <param name="idSposobuPlatnosci">Nieprawidłowa wartość właściwości IdSposobuPlatnosci.</param>
        public static SposubPlatnosci CreateSposubPlatnosci(global::System.Int32 idSposobuPlatnosci)
        {
            SposubPlatnosci sposubPlatnosci = new SposubPlatnosci();
            sposubPlatnosci.IdSposobuPlatnosci = idSposobuPlatnosci;
            return sposubPlatnosci;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSposobuPlatnosci
        {
            get
            {
                return _IdSposobuPlatnosci;
            }
            set
            {
                if (_IdSposobuPlatnosci != value)
                {
                    OnIdSposobuPlatnosciChanging(value);
                    ReportPropertyChanging("IdSposobuPlatnosci");
                    _IdSposobuPlatnosci = StructuralObject.SetValidValue(value, "IdSposobuPlatnosci");
                    ReportPropertyChanged("IdSposobuPlatnosci");
                    OnIdSposobuPlatnosciChanged();
                }
            }
        }
        private global::System.Int32 _IdSposobuPlatnosci;
        partial void OnIdSposobuPlatnosciChanging(global::System.Int32 value);
        partial void OnIdSposobuPlatnosciChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Opis
        {
            get
            {
                return _Opis;
            }
            set
            {
                OnOpisChanging(value);
                ReportPropertyChanging("Opis");
                _Opis = StructuralObject.SetValidValue(value, true, "Opis");
                ReportPropertyChanged("Opis");
                OnOpisChanged();
            }
        }
        private global::System.String _Opis;
        partial void OnOpisChanging(global::System.String value);
        partial void OnOpisChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Faktura_SposubPlatnosci", "Faktura")]
        public EntityCollection<Faktura> Fakturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Faktura>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "Faktura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Faktura>("Faktury2022Model.FK_Faktura_SposubPlatnosci", "Faktura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Status.
        /// </summary>
        /// <param name="idStatusu">Nieprawidłowa wartość właściwości IdStatusu.</param>
        public static Status CreateStatus(global::System.Int32 idStatusu)
        {
            Status status = new Status();
            status.IdStatusu = idStatusu;
            return status;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdStatusu
        {
            get
            {
                return _IdStatusu;
            }
            set
            {
                if (_IdStatusu != value)
                {
                    OnIdStatusuChanging(value);
                    ReportPropertyChanging("IdStatusu");
                    _IdStatusu = StructuralObject.SetValidValue(value, "IdStatusu");
                    ReportPropertyChanged("IdStatusu");
                    OnIdStatusuChanged();
                }
            }
        }
        private global::System.Int32 _IdStatusu;
        partial void OnIdStatusuChanging(global::System.Int32 value);
        partial void OnIdStatusuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_Kontrachenci_Status", "Kontrachenci")]
        public EntityCollection<Kontrachenci> Kontrachencis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Status", "Kontrachenci");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kontrachenci>("Faktury2022Model.FK_Kontrachenci_Status", "Kontrachenci", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Dokumentacja metadanych jest niedostępna.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Faktury2022Model", Name="Towar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Towar : EntityObject
    {
        #region Metoda tworząca
    
        /// <summary>
        /// Utwórz nowy obiekt Towar.
        /// </summary>
        /// <param name="idTowaru">Nieprawidłowa wartość właściwości IdTowaru.</param>
        public static Towar CreateTowar(global::System.Int32 idTowaru)
        {
            Towar towar = new Towar();
            towar.IdTowaru = idTowaru;
            return towar;
        }

        #endregion

        #region Właściwości proste
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTowaru
        {
            get
            {
                return _IdTowaru;
            }
            set
            {
                if (_IdTowaru != value)
                {
                    OnIdTowaruChanging(value);
                    ReportPropertyChanging("IdTowaru");
                    _IdTowaru = StructuralObject.SetValidValue(value, "IdTowaru");
                    ReportPropertyChanged("IdTowaru");
                    OnIdTowaruChanged();
                }
            }
        }
        private global::System.Int32 _IdTowaru;
        partial void OnIdTowaruChanging(global::System.Int32 value);
        partial void OnIdTowaruChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kod
        {
            get
            {
                return _Kod;
            }
            set
            {
                OnKodChanging(value);
                ReportPropertyChanging("Kod");
                _Kod = StructuralObject.SetValidValue(value, true, "Kod");
                ReportPropertyChanged("Kod");
                OnKodChanged();
            }
        }
        private global::System.String _Kod;
        partial void OnKodChanging(global::System.String value);
        partial void OnKodChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nazwa
        {
            get
            {
                return _Nazwa;
            }
            set
            {
                OnNazwaChanging(value);
                ReportPropertyChanging("Nazwa");
                _Nazwa = StructuralObject.SetValidValue(value, true, "Nazwa");
                ReportPropertyChanged("Nazwa");
                OnNazwaChanged();
            }
        }
        private global::System.String _Nazwa;
        partial void OnNazwaChanging(global::System.String value);
        partial void OnNazwaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StawkaVatSprzedazy
        {
            get
            {
                return _StawkaVatSprzedazy;
            }
            set
            {
                OnStawkaVatSprzedazyChanging(value);
                ReportPropertyChanging("StawkaVatSprzedazy");
                _StawkaVatSprzedazy = StructuralObject.SetValidValue(value, "StawkaVatSprzedazy");
                ReportPropertyChanged("StawkaVatSprzedazy");
                OnStawkaVatSprzedazyChanged();
            }
        }
        private Nullable<global::System.Decimal> _StawkaVatSprzedazy;
        partial void OnStawkaVatSprzedazyChanging(Nullable<global::System.Decimal> value);
        partial void OnStawkaVatSprzedazyChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StawkaVatZakupu
        {
            get
            {
                return _StawkaVatZakupu;
            }
            set
            {
                OnStawkaVatZakupuChanging(value);
                ReportPropertyChanging("StawkaVatZakupu");
                _StawkaVatZakupu = StructuralObject.SetValidValue(value, "StawkaVatZakupu");
                ReportPropertyChanged("StawkaVatZakupu");
                OnStawkaVatZakupuChanged();
            }
        }
        private Nullable<global::System.Decimal> _StawkaVatZakupu;
        partial void OnStawkaVatZakupuChanging(Nullable<global::System.Decimal> value);
        partial void OnStawkaVatZakupuChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cena
        {
            get
            {
                return _Cena;
            }
            set
            {
                OnCenaChanging(value);
                ReportPropertyChanging("Cena");
                _Cena = StructuralObject.SetValidValue(value, "Cena");
                ReportPropertyChanged("Cena");
                OnCenaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cena;
        partial void OnCenaChanging(Nullable<global::System.Decimal> value);
        partial void OnCenaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Marza
        {
            get
            {
                return _Marza;
            }
            set
            {
                OnMarzaChanging(value);
                ReportPropertyChanging("Marza");
                _Marza = StructuralObject.SetValidValue(value, "Marza");
                ReportPropertyChanged("Marza");
                OnMarzaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Marza;
        partial void OnMarzaChanging(Nullable<global::System.Decimal> value);
        partial void OnMarzaChanged();
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CzyAktywny
        {
            get
            {
                return _CzyAktywny;
            }
            set
            {
                OnCzyAktywnyChanging(value);
                ReportPropertyChanging("CzyAktywny");
                _CzyAktywny = StructuralObject.SetValidValue(value, "CzyAktywny");
                ReportPropertyChanged("CzyAktywny");
                OnCzyAktywnyChanged();
            }
        }
        private Nullable<global::System.Boolean> _CzyAktywny;
        partial void OnCzyAktywnyChanging(Nullable<global::System.Boolean> value);
        partial void OnCzyAktywnyChanged();

        #endregion

        #region Właściwości nawigacji
    
        /// <summary>
        /// Dokumentacja metadanych jest niedostępna.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Faktury2022Model", "FK_PozycjaFaktury_Towar", "PozycjaFaktury")]
        public EntityCollection<PozycjaFaktury> PozycjaFakturies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PozycjaFaktury>("Faktury2022Model.FK_PozycjaFaktury_Towar", "PozycjaFaktury");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PozycjaFaktury>("Faktury2022Model.FK_PozycjaFaktury_Towar", "PozycjaFaktury", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
